### ISSUE TITLE
Failed to activate the highlight-after-col package

### ISSUE THREAD

**Issue by CraZySacX** [rustyhorde/highlight-after-col#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Microsoft Windows 10 Pro
**Thrown From**: [highlight-after-col](https://github.com/rustyhorde/highlight-after-col) package, v0.1.0

### Stack Trace

Failed to activate the highlight-after-col package

```
At Cannot read property 'getRootScopeDescriptor' of undefined

TypeError: Cannot read property 'getRootScopeDescriptor' of undefined
    at HighlightAfterCol.module.exports.HighlightAfterCol.observeSettings (C:\Users\jozias\.atom\packages\highlight-after-col\lib\highlight-after-col.coffee:101:42)
    at HighlightAfterCol.observeSettings (C:\Users\jozias\.atom\packages\highlight-after-col\lib\highlight-after-col.coffee:3:61)
    at new HighlightAfterCol (C:\Users\jozias\.atom\packages\highlight-after-col\lib\highlight-after-col.coffee:30:12)
    at Object.module.exports.activate (C:\Users\jozias\.atom\packages\highlight-after-col\lib\main.coffee:14:25)
    at Package.module.exports.Package.activateNow (C:\Users\jozias\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package.js:243:19)
    at C:\Users\jozias\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package.js:224:30
    at Package.module.exports.Package.measure (C:\Users\jozias\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\jozias\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\jozias\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package-manager.js:486:21)
    at C:\Users\jozias\AppData\Local\atom\app-1.0.5\resources\app.asar\src\package-manager.js:469:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
highlight-after-col, v0.1.0
linter, v1.3.0
linter-rust, v0.2.6
project-manager, v1.15.11
tabs-to-spaces, v0.11.0
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by CraZySacX** [comment]
Closed.  null protected call.
